version: '3'

services:

  selenium:
    container_name: sandbox_codeception_selenium
    image: selenium/standalone-chrome
    ports:
      - '4444:4444'
    networks:
      - frontend

networks:
  frontend:
